### ISSUE TITLE
DeviceMeshView Support Master issue

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent/tt-metal#10755]
## Context:

Currently DeviceMesh represents a virtual device abstraction over a set of devices. Much of our testing today instantiates a DeviceMesh over all available devices on the system. This issue is to track the feature-support, issues and testing for instantiating a DeviceMesh over a subset of devices. 

## Motivation:
- This allows us to map existing T3K model tests to Galaxy Systems
- Simulate multi-host by having two independent device meshes instantiated on two separate processes
- User wants to independently create multiple DeviceSubMesh to schedule work onto
- User wants to only work on a smaller subset of devices for faster iteration time

## Issues:

- [x] Align on XY/YX orientation
- [ ] Allow offsets to be specified when creating submesh
- [ ] Testing across various device-submesh sizes
- [x] Visualize DeviceMesh
