### ISSUE TITLE
Report Microbenchmark and Performance Numbers to Developer Docs

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#10819]
Opening an issue so we can atleast start tracking this. More specifics need to be added but opening an issue will make it easier to get the ball rolling.

# Overview
There have been some explicit asks by the community for performance characteristics of various parts of our hardware and software stacks. 

e.g. from discord:
> "Is there a maximum # of tiles that the vector engine can chew through at a given time? If I wanted to achieve maximum throughput on a tensix core to simply add the tiles together, what would be the best parameters for the circular buffers? C =A+B where A,B,C are all tiles."

> "is there a chance TT can publish rough cycle counts for packing, unpack, tile ops and NoC latenct/throughput? I think it'll be helpful for the community writing kernels. Knowing how much operations can be done before math becoming the problem."

In addition to helping out these specific community members with their questions, having this information is good collateral for anyone curious about our hardware.

There's a lot of surface area for what we can report and what is meaningful to a user.

This issue is a master issue to track the collection and reporting of performance the various components:

# Proposal
I propose that we have multiple levels of performance reporting. 
- TTNN level
  - Performance reported for major ops by shapes/data types, other meaningful parametrizations
- TT-Metal level
  - Various base level primitives for moving data around and communicating 
- LLK level
  - Anything that the triscs touch

# Tasks
I propose we break the work down into 3 major phases:
1) "Just get it out there". Whatever performance numbers we have and for whatever components, let's publish them to the github repo as adhoc files.
  - Each set of numbers has some standard information also provided (described in phase 1)
2) Standardize the writing of microbenchmarks, locations of them and results, and how to run microbenchmarks
  - Process still manual
  - Add this as a step in the pull request process: performance numbers changed? Update the results
3) Automate it  

# Phase 0
- [ ] Add navigation to initial results for each component, from our root readmes

# Phase 1
Publish all existing numbers local to the scope of a given op or component. Don't worry about format or consistency - just get the existing numbers out there to the public. Pretty it up in phase 2.

I propose we adopt the following structure for the time being:
- In main repo README, perhaps under model performance numbers, add a single link to a microbenchmarks markdown file
  - This file can also be in root
- In microbenchmarks markdown, point to the correponding microbenchmarks markdown for each component: metal, ttnn, llk
  - Each component has their own microbenchmark markdown
    - We manually link to whatever microbenchmark numbers we have, which can be localized to individual ops
      - For example, under TT-Metal's performance markdown, I would link to various ethernet microbenchmark under `tests/tt_metal/microbenchmarks`  
      - For TTNN, I may link to performance results files with are local to each op. 
 
**For every result - point back to the original microbenchmark and simple instructions to run**
      
From the user navigation perspective, the experience is the same even if we decide to move results file locations

## Publish:
- [ ] Ethernet microbenchmarks:
  - [ ]  BW microbenchmark numbers (two microbenchmarks available)
  - [ ] Ethernet Link Latency
  - [ ] Ethernet Ring Latency
  - [ ] EDM Bandwidth
- [ ] NoC BW for reads/writes
- [ ] Matmul (DRAM bound)
- [ ] Matmul (compute bound)
  - [ ] by block shape - maybe this is actually LLK

Are others available right now?

# Phase 2
Start to mature the reporting process and produce the new benchmarks where applicable

## TTNN
I propose we create a new benchmarking directory in TTNN, as opposed to within each op. This gives us optionality to exclude microbenchmark code from release or other builds and also lets us more easily manage development of unified benchmarking infrastructure. Rather than custom benchmark infrastructure per op, it can be commonized for the component.

- [ ] design microbenchmark result organization
- [ ] build common microbenchmarking infrastructure

### Reports
  - Performance reported for major ops by shapes/data types, other meaningful parametrizations
    - Matmul
    - Convolutions
    - Eltwises
      - Activation Functions
    - CCLs
      - All gather
      - send/receive
      - reduce scatter
      - all reduce
    - views/slices
    - TMS:
      - reshapes
      - pad
      - unpad

### Reports:
  - DRAM reads/Writes (various configs: {interleaved,sharded} x {page sizes} x {tensor sizes} x {worker cores}
  - (remote) L1 reads/writes (see above)
  - (local) L1 reads/writes
  - noc commands by distance between endpoints
    - BW
    - Latency
  - Ethernet performance
    - BW
    - Ring Latency
    - Link Latency

### Reports:
  - pack performance (by data type, block size, etc.)
  - unpaack performance (see above)
  - math performance (I'm not familar all of the math LLKs available)
    - including various accumulation modes

# Phase 3
Move to auto-generation of numbers and automatic publishing of results
