### ISSUE TITLE
CCL Op Test Roadmap (Master Issue)

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#10873]
# Summary (Copy For All CCL Ops)
This set of tasks should be completed for each CCL operation, though progress for each op can be completed independently.

For a given op we improve test coverage by adding breadth (adding more shape and argument combinations) and adding depth (running given op variations across more topologies and scale-out configurations). Together these form a 2D matrix of test coverage.

# Adding Testing Depth
For a given test (list), enable the tests on various multichip configurations. Priorities may change over time and by op.

|hardware | topology | #links | #chips | #concurrent_instances | priority (0 highest)|
|-|-|-|-|-|-|
| n300  | line | x1 | 2 | 1 | 2 |
| n300  | ring | x1 | 2 | 1 | 2 |
| t3000 | ring | x2 | 4 | 1 | 1 |
| t3000 | ring | x1 | 4 | 2 | 1 |
| t3000 | ring | x1 | 8 | 1 | 0 |
| t3000 | line | x2 | 4 | 1 | 1 |
| t3000 | line | x1 | 4 | 2 | 0 |
| t3000 | line | x1 | 8 | 1 | 0 |
| TG    | line | x{1,2,3,4} | 8 | 1 | 0 |
| TG    | line | x4 | 8 | {1,2,4} | 0 |
| TG    | line | x{1,2,3} | 4 | 1 | 0 |
| TG    | line | x3 | 4 | 8 | 0 |
| TG    | ring | x3 | {4,8,16,32} | full_grid | 1 |
| TG    | ring | x3 | sweep | full_grid | 1 |
| TG    | line | x{3,4} | sweep | full_grid | 1 |
| TGG   | line | x{2,3,4} | sweep | full_grid | 1 |
| TGG   | ring | x{2,3,4} | sweep | full_grid | 1 |

In the case of sweeping, we enumerate the various ways to map lines and rings onto the given cluster. Below are some non-typical but valid test cases that should be included in the sweep:

<img width="1112" alt="image" src="https://github.com/user-attachments/assets/29ef7454-4d97-4fb6-acf4-89d8f40961b8">

# Adding Test Breadth
Sweep over:
- concat dim (prioritized as dim=3,2,1,0)
- tensor shape
  - including padding
- reduction operation (where applicable)
- datatype
- input/output tensor configs
  - layout {RM/Tile}x{Interleaved,Sharded}
  - Allocation {L1, DRAM}

# Tracking 
The following issues are tracked for various CCL Ops:

Note: All above tests should be rerun if bidireectional support is added to an operation

## All Gather
- [ ] #10874
- [ ] Mesh All Gather Test Sweeps
- [ ] Custom Topology Test Sweeps

## Reduce Scatter
- [ ] Line/Ring Reduce Scatter Test Sweeps
- [ ] Mesh All Gather Test Sweeps
- [ ] Custom Topology Test Sweeps

## All Reduce
- Add after op created

## Send/Receive
- Add after op created

**Comment by fahmedchanTT** [comment]
Closing due to lack of progress/updates. Please reopen as necessary. @ntarafdar
