### ISSUE TITLE
[Master issue] Fix all wheel installation issues

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#11133]
# List

- [x] https://github.com/tenstorrent/tt-metal/issues/10959
- [x] https://github.com/tenstorrent/tt-metal/issues/11782
- [x] https://github.com/tenstorrent/tt-metal/issues/11784
- [x] https://github.com/tenstorrent/tt-metal/issues/11854
- [x] https://github.com/tenstorrent/tt-metal/issues/10485
- [x] https://github.com/tenstorrent/tt-metal/issues/11132
- [x] https://github.com/tenstorrent/tt-metal/issues/9263
- [x] https://github.com/tenstorrent/tt-metal/issues/9305
- [x] https://github.com/tenstorrent/tt-metal/issues/12122
- [x] https://github.com/tenstorrent/tt-metal/issues/12273
- [x] https://github.com/tenstorrent/tt-metal/issues/12536
- [x] https://github.com/tenstorrent/tt-metal/issues/12538
- [ ] https://github.com/tenstorrent/tt-metal/issues/12707
- [x] https://github.com/tenstorrent/tt-metal/issues/12609

cc: @TT-billteng @dimitri-tenstorrent

**Comment by dimitri-tenstorrent** [comment]
Thank you @tt-rkim! I am in-flight on #11132 and the other two can definitely be helped by pointing the users to the Docker image with the wheels built-in.

**Comment by TT-billteng** [comment]
@ayerofieiev-tt
