### ISSUE TITLE
master todo list for HAL

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#11628]
FD ring buffer required memory map cleanup which required moving some things toward a HAL.  So a basic/minimal HAL now exists.  This issue tracks the additional work required to ~ complete it:
1) [] #4984 Finish moving memory map into HAL (underway)
2) Remove all uses of memory map addresses, use HAL instead
3) [] #10849 
4) [] #11830 Remove the remnants of common_runtime_address_map (eg, DRAM barrier, etc) into hal/elsewhere, create hal apis for things like L1/DRAM/PCIE alignment, remove external references
5) [] #11836 Create chip specification files for each chip in the hw/inc/<arch> dirs, this includes: number of core types, number of processors per core, dispatchable processor types, etc., extend the hal to read this file and set up tables used for iteration
6) [] #11839  Extend hal w/ build info for each processor type of each core.  This essentially is moving the build state in the device and the build options in build.cpp into the hal.  device would then query the hal to retrieve fw build info and send that to the build system (same for program.cpp for kernels)

**Comment by abhullar-tt** [comment]
Also adding: 
https://github.com/tenstorrent/tt-metal/issues/17275

**Comment by pgkeller** [comment]
closing this master issue, there is one open child issue but we'll track that on its own
