### ISSUE TITLE
[MCW] Tensor Parallel Implemenation of LLama3.1_8b on n300

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#11802]
Currently, in the main, we have [LLama3.1_8b](https://github.com/tenstorrent/tt-metal/tree/main/models/demos/wormhole/llama31_8b).

Exec Summary: (batch=32)
**MLP**
- [x] On n150 ([mlp_n150_perfs](https://github.com/user-attachments/files/16814808/n150_MLP_batch32_perf.csv)), t/s/u: 831.25 (1203.0 us latency), PCC=0.99
- [x] On n300 ([mlp_n300_without_TP_perfs](https://github.com/user-attachments/files/16814551/n300_MLP_batch32_withoutTP_perf.csv)), t/s/u: 830.76 (1203.7 us latency), PCC=0.99
- [x] With Tensor Parallelism in n300 ([mlp_n300_TP_perfs](https://github.com/user-attachments/files/16814530/n300_MLP_batch32_TP_perf.csv)), t/s/u: 1191.14 (839.5 us latency), PCC=0.99
_Using ttnn.line_all_gather on n300 as all_gather works in t3k only. Also set per_core_M = 1._

**RMSNorm**

- [x] On n150 ([rms_n150_perfs](https://github.com/user-attachments/files/16822144/n150_RMSNorm_perf.csv)), t/s/u: 15727.23 (63.6 us latency), PCC=0.99
- [x] On n300 ([rms_n300_without_TP_perfs](https://github.com/user-attachments/files/16822147/n300_RMSNorm_without_TP_perf.csv)), t/s/u: 15698.09 (63.7 us latency), PCC=0.99
- [x] With Tensor Parallelism in n300 ([rms_n300_TP_perfs](https://github.com/user-attachments/files/16822160/n300_RMSNorm_TP_perf.csv)), t/s/u: 28643.45 (34.9 us latency), PCC=0.99
- [ ] Distributed RMSNorm is currently blocked due to shape mismatch of inputs at ttnn.rms_norm_post_all_gather. branch: [harini/llama31_distributed_rmsnorm](https://github.com/tenstorrent/tt-metal/compare/harini/llama31_distributed_rmsnorm)

**Attention (Decode mode)**
generation length=1
- [x] On n150 ([n150_Attention_perf.csv](https://github.com/user-attachments/files/16851339/n150_Attention_perf.csv)), t/s/u: 2076.11 (481.7 us latency), PCC=0.99
- [x] On n300 ([n300_Attention_withoutTP_perf.csv](https://github.com/user-attachments/files/16851352/n300_Attention_withoutTP_perf.csv)), t/s/u: 2078.83 (481.0 us latency), PCC = 0.99
- [x] With Tensor Parallelism on n300 ([n300_attn_with_TP_perfs](https://github.com/user-attachments/files/16851365/n300_Attention_tensorparallel_perf.csv)), t/s/u: 3014.40 (331.7 us latency), current PCC = 0.73, To further improve PCC.

- [ ] Debugging Tensor Parallel Attention submodule in progress.
       - Improved PCC of  First Linear from 0.75 to 0.99, by changing input from ShardTensorToMesh to ReplicateTensorToMesh‎
       - Reshape PCC is 0.99, tested after changing input sharding
       - Improved PCC of nlp_create_qkv_heads from 0.03 to 0.50, by modifying the num_heads, num_kv_heads as per multi device
       - Replaced nlp_create_qkv_heads API with nlp_create_qkv_heads_decode API creating qkv heads in multi-device.
       - Modified the memory configs and program configs, which are parameters of nlp_create_qkv_heads_decode API referring to Mistral8x7b model
       - Currently stuck with the following error which using nlp_create_qkv_heads_decode API:
`RuntimeError: TT_FATAL @ ../ttnn/cpp/ttnn/operations/experimental/transformer/nlp_create_qkv_heads_decode/device/nlp_create_qkv_heads_decode_device_operation.cpp:32: input_tensor.shard_spec().value().shape[1] == (this->num_q_heads + this->num_kv_heads * 2) * this->head_dim || input_tensor.shard_spec().value().shape[1] == 32`
      - Updated debugging code changes to branch: [harini/llama31_attention](https://github.com/tenstorrent/tt-metal/compare/harini/llama31_attention)

**Decoder**
- [ ] Implement Tensor Parallel Decoder submodule
        - Implementing Tensor Parallel Decoder submodule in progress.
        - Facing shape mismtach error at linear op of MLP submodule.
        - Experimented on changing the input shards, gives shape mismatch at RMS submodule.
        - Further debugging the module to fix the issue.
       
- **WIP Branch:** [harini/llama31_n300_tensorparallel](https://github.com/tenstorrent/tt-metal/compare/harini/llama31_n300_tensorparallel)

Current Issues:

- RMS Norm: [12427](https://github.com/tenstorrent/tt-metal/issues/12427)
- Attention: [12428](https://github.com/tenstorrent/tt-metal/issues/12428)
- Decoder: [12429](https://github.com/tenstorrent/tt-metal/issues/12429)

- [x] Take Llama3.1_8b in main as reference. run it on n300 as is.
- [ ] To implement each sub-module in tensor-parallel implementation. (Needs to checkout all sub-tasks)
### sub-tasks
- [x] #11803
- [ ] #11804
- [ ] #11805
- [ ] #11806
- [ ] #11807
- [ ] #11808

Device: n300

**Comment by saichandax** [comment]
ToDo:

- Have perf sheet and FPS for n150 (ref point 1)
- n150 to n300 (on main) [ref point 2]
- Share the perfs for MLP sub-module.
- Continue with PCC analysis for MLP sub-module. Compare PCC on n300.

**Comment by mtairum** [comment]
N300 supported now in main. Check PR https://github.com/tenstorrent/tt-metal/pull/13160 for more details
