### ISSUE TITLE
[MCW] Data Parallel Implementation of ShallowUnet in n300

### ISSUE THREAD

**Issue by saichandax** [tenstorrent/tt-metal#11810]
Currently, on main we have Shallow Unet in old conv.

End goal is to have a data parallel implementation of Shallow Unet in n300 with new conv API.

### sub-tasks

- [ ] Port Shallow Unet with new Conv API on n150
- [ ] To run n150 version on n300 as is
- [ ] Enable Data parallelism for ShallowUnet on n300
- [ ] Performance improvements on n300

**Comment by saichandax** [comment]
ToDo:
* Double check model running on both devices
* Device perf to be 750 FPS
* Host perf using trace with 2cqs (on both n150 and n300)
* Validate Host side perf. Check with Austin.
* generalise and switch between n150 and n300

**Comment by saichandax** [comment]
Currently, this task is on hold. Updates are as of 28th August.

Currently Evan is working on Shallow Unet in #11912

**Comment by saichandax** [comment]
Closing the issue. No longer relevant.
