### ISSUE TITLE
Llama3 Decode Perf Burndown

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/tt-metal#12103]
This issue tracks the open issues the model team must solve in order to hit Llama2 perf targets.

## Decode 128
We have a new perf target of 20 tok/s at seqlen = 128. This issue lists the problems we will have to overcome to hit that target.

| milestone | single layer latency (ms) | full model latency (ms) | t/s/u |
|-|--------------------|-------------------|------|
|current performance | 0.753 | 60.24 | 16.6|
| target @ 100% | 0.625 | 50 | 20.0|
| projected after burndown | 0.623 | 49.84 | 20.06 |

Issues

- [ ] Bidirectional, 2-link AllGather (Sean) and optimized small AllGather
    - Saves 195us
- [ ] #6689 optimized matmul_1d (Yu Gao, Davor)
    - Saves 70us
    - Requires changes to prefill matmul_2d to support DRAM sharded weights
- [ ] #5562 ReduceScatter (Sean)
    - The big AllGather would get an additional 4x speedup with ReduceScatter. 
 - [x] #8060 faster RMSNorm (Yu Gao)
    - Could save 10 us
- [x] Fold pad/transpose into `create_nlp_heads` (Kevin/Jack)
    -  **Saves 30 us**.
- [x] Fold transpose/unpad into `concat_nlp_heads` (Kevin/Jack)
    -  **Saves 30 us**.
- [x] 1 GHz clock
    - expected 1.25x speedup. Got 1.2x 
- [x] #7379 unpad with output sharded (Jack)
    - Important for seqlen=2k. No large gain for 128
- [x] #7208 faster exp

## Prefill 2k
We focus on 2k prefill for the same reason we focus on 2k decode. It is the tougher regime and needs more attention than smaller seqlen prefills.

Issues: 

- [ ] #6689 optimized matmul_2d (Yu Gao, Davor)
   - Saves 1.8 ms @ 800 MHz
- [ ] ReduceScatter (Sean)
   - 2x faster than AllGather, saves 1.8 + .8 = 2.6 ms
- [ ] Overlapped CCL (Sean, Colman)
   - Could save up to 4.8 ms for perfect overlapping
- [x] #7461 Optimized SDPA, flash-attention style (Colman)
   - Saves 1.5 ms
- [x] Optimized ROPE (Colman)
   - Saves .4 ms
- [x] 1 GHz clock
    - 1.25x speedup
- [ ] Distributed Layernorm (@cglagovichTT @johanna-rock-tt )

| milestone | single layer latency (ms) | full model latency (ms) | t/s |
|-|--------------------|-------------------|------|
|current performance | 20.16 | 1612.8 | 1270.5|
| target @50% |6.84 | 547 | 3745|
| projected after burndown | 7.24 | 579.2 | 3537.1|

**Comment by cglagovichTT** [comment]
Sheet: https://docs.google.com/spreadsheets/d/1dF0eT33eh6d5OURSMSiWv5mIBReE4-DvJ82_nao7G_E/edit?gid=95984160#gid=95984160

**Comment by uaydonat** [comment]
fyi @davorchap

**Comment by cglagovichTT** [comment]
Updated sheet after applying fused AllGather matmul + CCL team's various optimizations. Summary: still dispatch bound, and device dispatch fully explains the difference between device perf and e2e perf

![image](https://github.com/user-attachments/assets/c1e0891f-37fb-4e16-aca4-46c7f20d4cf7)

**Comment by cglagovichTT** [comment]
2.5-3 weeks low latency drop on t3k (ring buffer)
Turn of eth dispatch for a win (8x7 grid) -- reduces prefetcher and dispatch buffering, hurts BW to DRAM

**Comment by cglagovichTT** [comment]
Paul merged worst-case dispatch optimization last night.
Aditya is going to merge in a few days which undoes the optimization.
