### ISSUE TITLE
Flash Attention and Flash Decode GQA (and MQA) Improvements: Master Issue

### ISSUE THREAD

**Issue by caixunshiren** [tenstorrent/tt-metal#12330]
To improve usability of the op and support functionalities in #12102 , I would like to have the following improvements on Flash Decode GQA:

Round 1:
- [x] Support transpose_q, which both q of shape [1 x qh x b x h] and [1 x b x qh x h] are supported as input
- [x] Support GQA on a shared cache, which KV of shape [1 x kh x s x h] is supported
- [x] Add support for tensor indices for GQA

Round 2 (Major changes + refactoring):
Turns out that to enable paged attention support for GQA, we need to natively support group heads in flash decode rather than doing our current way of work around. Below are the set of tasks:
- [x] Change flash decode to take in cache with shape [b x nkv x S x d] rather than current [nkv x b x S x d]
- [x] Add multi-kv head (GQA) support for flash decode
- [x] Add multi-kv head (GQA) support for paged flash decode
- - Few limitations. (1) sharded output is not supported due to complications. (2) it asserts num_cores >= batch*num_kv_heads. These features will be added in future prs
- [x] Refactor GQA -- either get rid of the op or have it alias to flash decode

Round 3:
- [x] Support case num_cores < batch*num_kv_heads for flash decode GQA

Round 3.5:
- [x] Support program caching for page table tensor: #13365

Round 4:
- [x] Fix diverging PCC for SDPA family kernels #13866
- [x] Support FP32 Accumulate: #13364

Round 5:
- [x] Deprecate and remove flash decode gpa op
- [x] Support non-causal mode with attention masks in flash decode: #14008

Round 6:
- [x] Improve multi-core parallelization on small batch and heads in flash decode: https://github.com/tenstorrent/tt-metal/issues/14103

Lower Priority:
- [ ] Support sharded output for flash decode GQA
- [ ] Support bfp4/8_b input for flash decode GQA
- [ ] Expose the shared cache feature on MQA flash decode as well
- [ ] Support share cache feature for page attention (both MQA and GQA)

Ongoing Issues:
- [x] https://github.com/tenstorrent/tt-metal/issues/9608

**Comment by minaliuTT** [comment]
@ekuslysTT Can you check if this ticket is still relevant? Thanks!

**Comment by ekuslysTT** [comment]
Closing after reviewing with @alingTT . To be re-opened if needed.
