### ISSUE TITLE
[Blackhole Ops] Fast Dispatch Post Commit Issue Master List

### ISSUE THREAD

**Issue by abhullar-tt** [tenstorrent/tt-metal#12349]
This is a master list of all tests that needed to be disabled to enable passing `fast-dispatch-build-and-unit-tests.yaml` on BH

Goal: Remove instances of `skip_for_blackhole` that are not skipped for WH

**Matmul**
- [x] test_bert_ops.py::test_bert_linear_batch4 hanging #12597
- [x] sweep_tests/pytests/helper_funcs/test_linear.py::test_linear_with_bias PCC failure with input shape [1, 1, 64, 128] #12539
- [x] misc/test_bert_ops.py::test_bert_linear_batch4_fp32_input_output hanging #12598
- [x] misc/test_attn_matmul.py hanging #12599
- [x] test_sharded.py::test_sharded_matmul_2d hanging #12600
- [x] misc/test_tilize_hpadding_matmul.py hanging #12601
- [x] misc/test_tilize_matmul.py hanging #12602
- [x] misc/test_matmul_dram_sharded.py segfault #12603
- [x] sweep_tests/pytests/tt_dnn/test_matmul.py::test_run_matmul_test some configs hanging #12604
- [x] unit_testing/misc/test_sharded.py::test_resharded_binary_to_matmul hanging - will be fixed with other matmul hangs with #13981 

**Softmax**
- [x] misc/test_softmax_sharded.py::test_scale_mask_softmax_rm mismatch https://github.com/tenstorrent/tt-metal/issues/14350
- [x] misc/test_single_core_fused_ops.py::test_softmax mismatch https://github.com/tenstorrent/tt-metal/issues/14351

**LayerNorm**
- [x] misc/test_distributed_layernorm_post_allgather.py mismatching https://github.com/tenstorrent/tt-metal/issues/14354
- [x] misc/test_single_core_fused_ops.py::test_layernorm mismatching https://github.com/tenstorrent/tt-metal/issues/14355

**Moreh Ops**
- [ ] misc/test_moreh_getitem.py mismatching
- [x] misc/test_moreh_sum.py::test_moreh_sum_integer mismatching
- [ ] misc/test_moreh_layernorm.py::test_moreh_layernorm_backward mismatching
- [ ] misc/test_moreh_nll_loss.py mismatching
- [ ] misc/test_moreh_nll_loss_unreduced.py mismatching

**Loss Ops**
- [ ] unit_testing/loss_ops/test_loss_mae.py mismatching
- [ ] unit_testing/loss_ops/test_loss_mse.py mismatching

**Downsample**
- [ ] unit_testing/misc/test_downsample.py mismatching

**Multi Op**
- [ ] misc/test_create_qkv_heads.py::test_nlp_create_qkv_heads_test l1 buffer and cb crash
- [ ] misc/test_scaled_dot_product_attention.py mismatching - only test failing is the one using hi-fidelity/float32 for calculations. may be similar to other float32 issues.
- [ ] misc/test_scaled_dot_product_attention_decode.py
- [ ] misc/test_nlp_create_qkv_heads_decode.py requires eth connected devices

**Rotary Embeddings** (not a TM, does a positional transformation using a matmul)
- [x] #14064
- [ ] #14062

**TMs**
- [x] i2s_s2i tests for maxpool2d #12184 (works , running pipelines and then merge)
- [x] misc/test_reshape.py::test_tile_major_reshape mismatch  #12548 
- [x] misc/test_reshard.py assertion in reshard op #12546 
- [x] misc/test_sharded.py hangs #14745 
- [x] #14059
- [x] misc/test_repeat.py::test_repeat hitting op assert (skipping failing case on branch) https://github.com/tenstorrent/tt-metal/issues/14518
- [x] unit_testing/misc/test_bcast.py (re-tested with latest main on 10/27 and works, pending enabling on CI)
- [x] sweep_tests/pytests/tt_dnn/test_transpose.py mismatching on BH
- [x] sweep_tests/pytests/tt_dnn/test_pad.py https://github.com/tenstorrent/tt-metal/issues/14456
- [x] sweep_tests/pytests/tt_dnn/test_untilize_with_unpadding.py (fixed on branch) https://github.com/tenstorrent/tt-metal/issues/14548
- [x] misc/test_transpose.py::test_transpose_bfloat8_b (Saad's transpose_hc fixes also fix issue here)
- [x] misc/test_min_max.py mismatching (Saad's transpose_hc fixes also fix issue here)
- [x] #14061
- [x] sweep_tests/pytests/tt_dnn/test_repeat_interleave.py https://github.com/tenstorrent/tt-metal/issues/14754 (might be a transpose issue, depending on dim )
- [x] sweep_tests/pytests/tt_dnn/test_permute.py mismatching #12550 
- [x] misc/test_transpose.py mismatching #12549 (fixed 1/2 issues here)
 

**LLKs**
- [x] misc/test_attn_matmul.py failing #13875 
- [x] misc/test_softmax.py::test_softmax PCC failure with float32 #14348
- [x] misc/test_softmax.py::test_scale_mask_softmax_inplace mismatch https://github.com/tenstorrent/tt-metal/issues/14349
- [x] misc/test_layernorm.py::test_layernorm_mix_precision mismatch https://github.com/tenstorrent/tt-metal/issues/14352
- [x] misc/test_layernorm_sharded.py mismatch https://github.com/tenstorrent/tt-metal/issues/14353
- [x] misc/test_rotary_embedding.py::test_rotary_embedding_decode fails for Bfloat8_b #14063, compute kernel scalar multiplication returns wrong values
- [x] https://github.com/tenstorrent/tt-metal/issues/14594
- [x] https://github.com/tenstorrent/tt-metal/issues/14063
- [x] https://github.com/tenstorrent/tt-metal/issues/14064
- [x] https://github.com/tenstorrent/tt-metal/issues/14352
- [x] https://github.com/tenstorrent/tt-metal/issues/14348
- [x] https://github.com/tenstorrent/tt-metal/issues/14349
- [x] https://github.com/tenstorrent/tt-metal/issues/14353
- [x] https://github.com/tenstorrent/tt-metal/issues/14354
- [x] https://github.com/tenstorrent/tt-metal/issues/15106
- [x] https://github.com/tenstorrent/tt-metal/issues/14350
- [x] https://github.com/tenstorrent/tt-metal/issues/15756

**Reduce**
- [x] Reduce in test_sharded.py PCC failure for BH https://github.com/tenstorrent/tt-metal/issues/15106

**Misc.** 
- [ ] misc/test_update_cache.py
- [x] unit_testing/test_prod_nc.py mismatch
- [x] #12574
- [x] misc/test_sum.py mismatch
- [x] #12577

**Sweeps**
- [x] #12584
- [x] #12585
- [x] #12589
- [ ] sweep_tests/pytests/tt_dnn/test_prod.py mismatching
- [x] #12591
- [x] #12592
- [x] sweep_tests/pytests/tt_dnn/test_round.py mismatching on BH
- [x] sweep_tests/pytests/tt_dnn/test_stats.py mismatching on BH
- [x] sweep_tests/pytests/tt_dnn/test_sum.py mismatching on BH
- [x] sweep_tests/pytests/tt_dnn/test_unary_floor_div.py mismatching on BH
- [x] #12586
- [x] #12588
- [x] #12590

**Comment by ayerofieiev-tt** [comment]
@mywoodstock @tarafdarTT @sjameelTT @bbradelTT @yugaoTT @razorback3 FYI

**Comment by smehtaTT** [comment]
FYI - CNN list for Blackhole tracked at - https://github.com/tenstorrent/tt-metal/issues/11124

**Comment by tarafdarTT** [comment]
@abhullar-tt I updated the list including my individual issues tracking this.

**Comment by yugaoTT** [comment]
Lots of tests fail when input is float32 format, is it not supported or buggy on BH?

**Comment by abhullar-tt** [comment]
> Lots of tests fail when input is float32 format, is it not supported or buggy on BH?

@rtawfik01 @nvelickovicTT do you know if there are issues with float32?

**Comment by rtawfik01** [comment]
@yugaoTT float32 has been tested in blackhole, can you provide the simplest test case that fails with float32? Preferably a single-tile case? Its more likely a metal api issue, and the fp32 flag is not passed to blakchole llks fully

**Comment by caixunshiren** [comment]
It would be good to also test the flash decode op, as it is being used in every LLM's decode mode.
Link to the test case: https://github.com/tenstorrent/tt-metal/blob/main/tests/tt_eager/python_api_testing/unit_testing/misc/test_scaled_dot_product_attention_decode.py

**Comment by cglagovichTT** [comment]
Adding to Jack's comment, there are a few more ops which we need functional on BH.
**multi op**
misc/test_scaled_dot_product_attention_decode.py
misc/test_nlp_concat_heads_decode.py

**paged cache ops**
tests/ttnn/unit_tests/operations/test_paged_update_cache.py

CCL tests for AllGather/ReduceScatter (@SeanNijjar, which test files should we point to?)

**Comment by skhorasganiTT** [comment]
These ops from Falcon7b seem to be missing, it would be good to double check if they're failing as well:
- ttnn.experimental.nlp_create_qkv_heads_falcon7b (tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_create_qkv_heads.py)
- ttnn.experimental.nlp_concat_heads (tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_concat_heads.py)

**Comment by uaydonat** [comment]
> > These ops from Falcon7b seem to be missing, it would be good to double check if they're failing as well:
> > 
> > * ttnn.experimental.nlp_create_qkv_heads_falcon7b (tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_create_qkv_heads.py)
> > * ttnn.experimental.nlp_concat_heads (tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_concat_heads.py)
> 
> BH post commit will run everything that post commit on main runs, unless explicitly tagged with `skip_for_blackhole` so we shouldn't have to do any additional checks. Currently BH post commit is down because of some FW issues but once it is back up I can check the status of it

Thanks @abhullar-tt 
We can use the feedback from Colman, Salar, etc. as a sanity check. After running the BH post commit, we should double check that these ops are on the list. If they are missing, then we should re-evaluate our testing coverage.

**Comment by abhullar-tt** [comment]
> > > These ops from Falcon7b seem to be missing, it would be good to double check if they're failing as well:
> > > 
> > > * ttnn.experimental.nlp_create_qkv_heads_falcon7b (tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_create_qkv_heads.py)
> > > * ttnn.experimental.nlp_concat_heads (tests/tt_eager/python_api_testing/unit_testing/misc/test_nlp_concat_heads.py)
> > 
> > 
> > BH post commit will run everything that post commit on main runs, unless explicitly tagged with `skip_for_blackhole` so we shouldn't have to do any additional checks. Currently BH post commit is down because of some FW issues but once it is back up I can check the status of it
> 
> Thanks [@abhullar-tt](https://github.com/abhullar-tt) We can use the feedback from Colman, Salar, etc. as a sanity check. After running the BH post commit, we should double check that these ops are on the list. If they are missing, then we should re-evaluate our testing coverage.

BH post commit is clean on main and the ops listed by Salar are covered. From Colman's list:
- misc/test_scaled_dot_product_attention_decode.py is skipped on BH so it has been added to top list
- misc/test_nlp_concat_heads_decode.py is included in post commit tests 
- tests/ttnn/unit_tests/operations/test_paged_update_cache.py --> not sure where this gets tested @cglagovichTT

**Comment by cglagovichTT** [comment]
paged update cache is tested in this postcommit pipeline https://github.com/tenstorrent/tt-metal/actions/runs/11815965526/job/32918624681#logs

**Comment by smehtaTT** [comment]
@prajaramanTT  to confirm this can be closed

**Comment by smehtaTT** [comment]
@abhullar-tt  - can you confirm if this can be closed? Have we absorbed all these opens into other open issues? thanks

**Comment by ejouretTT** [comment]
@cmaryanTT to go through Moreh details and make sure captured elsewhere - not high priority for launch. Then close this ticket.

**Comment by bbradelTT** [comment]
> Yes I think enough ops work on BH. Maybe separate issues wherever we “skip_for_blackhole” is added in op tests [@cmaryanTT](https://github.com/cmaryanTT)

We have https://github.com/tenstorrent/tt-metal/issues/18485 to keep track of failures and issues shouldn't be closed until the corresponding skip is removed.

If someone has skips outside of that hopefully they add to that or track with their own issues.
