### ISSUE TITLE
Add tests for dprint_tensix_dest_reg

### ISSUE THREAD

**Issue by miacim** [tenstorrent/tt-metal#13052]
### Description:

We need to develop tests for the dprint_tensix_dest_reg function, which uses dbg_get_array_row to read dest register and DPRINT to print tiles from the dest register.  Currently, there are no tests written for this functionality.

### Objective:

- Write tests that use the existing infrastructure to load kernels, invoke the dprint_tensix_dest_reg function, and capture the output.
- Verify that the printed output matches the expected values based on the data loaded into the dest register.
- Lay the groundwork for future enhancements and debugging, acknowledging any known issues without focusing on them in this task.
 
### Tasks:
- [x] 1. 1. Familiarize with Dest Register and Data Retrieval Functions
  - [x] Understand data storage in dest registers: How data is stored within the dest registers, how it depends on data type and how modes affect it.
  - [x] Review function for reading data from dest register: Analyze the dbg_get_array_row function, understand how it retrieves data and how that data should be interpreted, and note any limitations
  - [x] #15533
- [x] 2. Develop Kernel to Load Data into Dest and Invoke dprint_tensix_dest_reg
  - [x] Write kernel that can load data into dest and uses dprint_tensix_dest_reg to print tiles in dest. View ```tests/tt_metal/tt_metal/test_kernels/compute/eltwise_copy.cpp```.
- [x] 3. Implement Basic Unit Test:
  - [x] Write basic unit tests that will use new kernel. 
  - [x] Use simple known data patterns (eg. sequential numbers or any specific pattern) to facilitate verification. View ```create_arange_vector_of_bfloat16```
  - [x] Define expected outputs for test
  - [x] Capture and parse console output
- [x] 4. Special tests
  - [x] Write test that will test different dest data formats (float16_b, Float32)
  - [x] Write test that will test dest remap on Blackhole #12234  

fyi @ttmtrajkovic
