### ISSUE TITLE
CCL Fabric Migration Master Issue

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#13223]
This issue outlines the work to migrate CCL ops and EDM to the Tenstorrent (Multichip) Fabric. The tt-fabric will be a cluster spanning fabric that will implement routing functionality and support basic fabric commands. This issue doesn't outline the extent of the fabric capabilities - only the path to get EDM and CCL ops migrated there.

- [ ] Add fabric queue to EDM as its channel implementation
The fabric will use a different queuing mechanism than the current EDM. The current EDM breaks a channel into one or more buffers where the EDM advances a full buffer per transaction. It does not increment rd/wr pointers as different payloads are sent through the channel. EDM will be updated to use this new queueing mechanism

- [ ] Update the WorkerEdmAdaptors to work with this new queue
Pointer management will differ from before so the underlying implementation will need to change to match

- [ ] Add EDM push support to the output side
Currently EDM can only be pushed to or pulled from. For fabric, it will need to push from.
  - This can be exposed as a special (compile time decided) mode for the EDM during the transition period 
- [ ] Continuation of above: Add write address to EDM packets
  - EDM will use this for destination address
  - TBD: How is the header structured to specify this information?

- [ ] Expose persistent mode for fabric use
EDM will not be torn down for fabric

- [ ] (Performance) Add direct side channel to EDM for low-latency mode

**Comment by SeanNijjar** [comment]
stale
