### ISSUE TITLE
SubDevice Implementation Master Issue

### ISSUE THREAD

**Issue by tt-aho** [tenstorrent/tt-metal#13655]
- [x] SubDevice object
  - Vec of CoreRangeSets by CoreType

- [ ] SubDeviceManager Object
  - [x] Allocator changes to support reduced size global L1 allocator, and local SubDevice allocators
  - State required to be tracked per manager
    - [ ] Data generated by program finalize
    - [ ] FD program cmd cache. Most of the work is done for this after refactor for #13588 
    - [x] Metal trace buffer map
    - [x] Worker counters (we need a set maximum since counters are in L1)
    - [x] WorkerConfigBufferMgr
  - [x] APIs for Create/Load/Clear of CoreMeshManager
  - [x] Event/finish APIs need to take in SubDevices to block on
  - [ ] Program spanning multiple sub-devices (not needed for llama?)
    - [x] CB validation needs to be across used sub-devices
    - [ ] Syncing/levelling of ring buffers for semaphores

Potential dependencies for feature completeness of SubDevice
- [ ] Refactor of program to separate api and state
    - Potentially needed since we only finalize programs once, but recompiling for a different device may have different commands, so we need to track state by device. May not be immediately needed since op infra does not recompile a program across multiple devices
- [ ] API changes for accessing rtas/updating ptrs (ETA ?)
    - Needed for generality of running the same program with different SubDeviceManagers loaded. May not be immediately needed for Llama deadline

Potentially needed features that depend on SubCoreMesh:
- [x] #14741
- [x] #14108

**Comment by pgkeller** [comment]
@tt-aho is this still in flight or resolved at this point?

**Comment by tt-aho** [comment]
There are a few outstanding features we specced out to support, but wasn't immediately needed for llama support. I can just spin those as separate issues and close this one?

**Comment by pgkeller** [comment]
yes, let's close this and file dedicated issues for the remaining todos, thanks

**Comment by tt-aho** [comment]
Filed as #19835 and #19836
