### ISSUE TITLE
Eltwise Master Tracking

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#13795]
https://docs.google.com/spreadsheets/d/1MWzDkcmI_Jq4xeQAcrXnd7BpyD7o66RpvuE6dKNoBb8/edit?gid=0#gid=0

### PyTorch2 Tracing Generality
- [x] #13521 

### Master issue for work needed on LLKs
- [x] #9702
- [ ] #14077

### Layout Issues
- [x] #13854<!-- ,ttnn.div_bw unary inconsistent documentation regarding input tensors layout,GS, WH, op_cat: eltwise, backward,2024-10-16T08:19:12Z -->
- [x] #13928<!-- ,ttnn.ldexp_bw operation does not work with row major layout,bug, GS, WH, op_cat: eltwise,2024-10-17T09:00:15Z -->

### Scalar Issues
- [x]  #13644<!-- , Binary op with scalar is very slow  -->
- [x] #13864<!-- ,Support for tensor-scalar variant in ttnn.maximum and ttnn.minimum,op_cat: eltwise, MCW,2024-10-16T11:31:49Z -->


### Broadcasting
- [x] #6445<!-- ,Eltwise / Reduce / Broadcast Related tasks/bugs - MCW,operations, feature, op_cat: eltwise,2024-10-17T05:12:01Z -->
- [x] #12798<!-- ,[Bug Report] Multiply and divide has different broadcasting rules,bug, P1_critical, op_cat: eltwise,2024-10-02T10:38:17Z -->
- [x] #13464<!-- ,eltwise ops fail PCC when broadcasting [GS][WH],bug, models, op_cat: eltwise, LLM_bug, Op Generalization, llama3,2024-10-11T09:11:32Z -->
- [x]  #13643<!-- , Binary operations which require ttnn::repeat are very slow -->
- [ ]  #13566<!-- ,TTNN throws an exception if second operand of binary Ops require broadcast,bug, op_cat: eltwise, forge,2024-10-14T09:32:51Z -->


### Blackhole Issues
- [x] #12577<!-- ,misc/test_unary_ops_ttnn.py::test_unary_pow_ttnn,bug, blackhole, op_cat: eltwise,2024-09-12T15:12:39Z -->
- [x] #12584<!-- ,sweep_tests/pytests/tt_dnn/test_bitwise_or.py mismatch,bug, blackhole, op_cat: eltwise,2024-09-12T15:34:18Z -->
- [x] #12585<!-- ,sweep_tests/pytests/tt_dnn/test_bitwise_xor.py mismatch,bug, blackhole, op_cat: eltwise,2024-09-12T15:35:18Z -->
- [x] #12586<!-- ,sweep_tests/pytests/tt_dnn/test_div.py only supported on WH,bug, blackhole, op_cat: eltwise,2024-09-12T15:36:53Z -->
- [x] #12588<!-- ,sweep_tests/pytests/tt_dnn/test_unary_div.py only supported on WH,bug, blackhole, op_cat: eltwise,2024-09-12T15:37:46Z -->
- [x] #12589<!-- ,sweep_tests/pytests/tt_dnn/test_floor_div.py only supported on WH,bug, blackhole, op_cat: eltwise,2024-09-12T15:38:46Z -->
- [x] #12590<!-- ,sweep_tests/pytests/tt_dnn/test_frac.py unsupported on BH,bug, blackhole, op_cat: eltwise,2024-09-12T15:40:33Z -->
- [x] #12591<!-- ,sweep_tests/pytests/tt_dnn/test_remainder.py unsupported on BH,bug, blackhole, op_cat: eltwise,2024-09-12T15:49:59Z -->
- [x] #12592<!-- ,sweep_tests/pytests/tt_dnn/test_right_shift.py mismatching on BH,bug, blackhole, op_cat: eltwise,2024-09-12T15:54:18Z -->


### Bugs: Unsupported Operations or Features Generality
- [x]  #13779<!-- ,Support floating-point exponents for `ttnn.pow`,bug, precision, op_cat: eltwise, perf,2024-10-15T00:42:11Z -->
- [x]  #13758<!-- ,[Feature Request] DPS version of logical_xor op,feature-request, op_cat: eltwise, forge,2024-10-17T20:27:25Z -->
- [x]  #13646<!-- ,Ttnn::multiply does not broadcast in second dimension -->
- [x] #14099


### Bugs: Mixed Precisions
- [x]  #13625<!-- ,ttnn.lerp operation does not work with mixed precaution,bug, op_cat: eltwise,2024-10-09T08:55:32Z -->
- [x]  #13930<!-- ,ttnn.logaddexp_bw operation fails with low PCC when tensors are in mixed precisions,bug, GS, WH, op_cat: eltwise,2024-10-17T09:07:32Z -->


### Invalid Results
- [x] #6583<!-- ,[Bug Report] invalid acosh backward result,bug, moreh, P1_critical, op_cat: eltwise, backward,2024-06-05T07:30:18Z -->
- [x] #6633<!-- ,[Feature Request] Improvement Needed for Unit Tests,bug, moreh, P1_critical, op_cat: eltwise,2024-04-16T04:01:14Z -->
- [x] #6672<!-- ,[Bug Report] invalid isclose result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-04-02T14:20:14Z --> -->
- [x] #6720<!-- ,[Bug Report] Invalid recip result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-10-14T15:33:08Z -->
- [x] #6721<!-- ,[Bug Report] Invalid log result,bug, moreh, LLK, P1_critical, op_cat: eltwise, forward,2024-10-01T00:51:05Z -->
- [x] #6722<!-- ,[Bug Report] invalid asin result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-10-14T13:30:10Z -->
- [x] #6723<!-- ,[Bug Report] invalid acos result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-10-14T13:31:36Z -->
- [x] #6724<!-- ,[Bug Report] invalid isfinite result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-04-04T08:13:37Z -->
- [x] #6725<!-- ,[Bug Report] invalid isinf result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-06-05T07:27:56Z -->
- [x] #6726<!-- ,[Bug Report] invalid isposinf result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-04-04T08:06:39Z -->
- [x] #6727<!-- ,[Bug Report] invalid isneginf result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-04-03T08:09:21Z -->
- [x] #6728<!-- ,[Bug Report] invalid signbit result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-10-17T12:13:26Z -->
- [x] #6735<!-- ,[Bug Report] invalid tan result,bug, moreh, P1_critical, op_cat: eltwise, forward,2024-08-09T08:24:36Z -->
- [x] #6991<!-- ,[N300] TTNN Unit Test Failures: Op PCC failures,bug, op_cat: eltwise, op_cat: reduces, ttnn-unit-tests,2024-10-16T04:58:35Z -->
- [x] #7488<!-- ,Multiple operations are handling inf/nan values differently that pytorch,bug, GS, WH, op_cat: eltwise,2024-09-30T23:20:32Z -->
- [x] #8544<!-- ,Implement PReLU correctly,bug, op_cat: eltwise,2024-09-30T23:30:23Z -->
- [x] #8593<!-- ,TTNN pow - fail when input tensor BFLOAT8_B and exponent is scalar float,bug, GS, WH, op_cat: eltwise,2024-10-16T15:31:38Z -->
- [x] #8594<!-- ,TTNN pow breaks when exponent is tensor,bug, GS, WH, op_cat: eltwise,2024-09-30T23:31:45Z -->
- [x] #9702<!-- ,Binary op blockers. Kernel writing needed.,bug, op_cat: eltwise, forward, master, MCW,2024-09-30T23:12:32Z -->
- [x] #9985<!-- ,TT_LIB eltwise_addcmul - fail if one of the tensor arguments is on the host device (GS and WH),bug, GS, WH, op_cat: eltwise,2024-09-30T23:15:33Z -->
- [x] #10034<!-- ,Binary Shift operators,op_cat: eltwise,2024-10-01T17:22:08Z -->
- [x] #10035<!-- ,Binary Bitwise ops,op_cat: eltwise,2024-10-09T17:08:31Z -->
- [x] #10081<!-- ,TTNN eltwise_acosh - fail when input tensor has ROW_MAJOR layout (GS and WH),bug, GS, WH, op_cat: eltwise,2024-10-01T00:01:40Z -->
- [x] #10141<!-- ,TTNN eltwise_atanh - fail when input tensor has ROW_MAJOR layout (GS and WH),bug, GS, WH, op_cat: eltwise,2024-10-01T00:01:57Z -->
- [x] #10160<!-- ,TTNN eltwise_acosh fails with Fatal Python error: floating point exception when input tensor has a shape [3, 1, 22, 12] and a ROW_MAJOR layout,bug, GS, WH, op_cat: eltwise,2024-10-01T00:02:57Z -->
- [x] #12253<!-- ,Batch normalization support,feature-request, op_cat: eltwise, community, pytorch-compiler,2024-10-15T01:00:21Z -->
- [x] #13234<!-- ,Support clamping with min/max tensor,P1_critical, feature, op_cat: eltwise, pytorch-compiler,2024-10-14T13:34:55Z -->
- [x] #12671<!-- ,Some pointwise unary ops return 2-D results from 1-D inputs,bug, P1_critical, op_cat: eltwise, pytorch-compiler,2024-10-13T15:28:43Z -->
- [x] #12815<!-- ,ttnn.mish operation kernel duration is high,bug, P0_Showstopper, op_cat: eltwise, Customer_Bug, yolov4, mcw_cst,2024-09-26T13:21:43Z -->
- [x] #12835<!-- ,Incorrect results with `fmod` and `remainder` from negative inputs,bug, op_cat: eltwise, community,2024-10-01T08:34:54Z -->
- [x] #12907<!-- ,Tensor–tensor bitwise operators,feature-request, op_cat: eltwise, community, pytorch-compiler,2024-10-15T00:53:49Z -->
- [x] #12936<!-- ,Unsupported cases for `aten.amin/amax` conversion,bug, P1_critical, op_cat: eltwise, pytorch-compiler,2024-10-11T05:14:51Z -->
- [x] #12937<!-- ,Unsupported cases for `aten.var.correction` conversion,bug, op_cat: eltwise, pytorch-compiler,2024-10-01T00:06:36Z -->
- [x] #12939<!-- ,Unsupported cases for `aten.prod.dim_int` conversion,bug, P1_critical, op_cat: eltwise, pytorch-compiler,2024-10-03T04:58:08Z -->
- [x] #13186<!-- ,[Bug Report] ttnn.max - Unsupported dim,bug, P1_critical, op_cat: eltwise, community,2024-10-14T13:35:19Z -->
- [x] #13337<!-- ,Suboptimal trigonometric functions,bug, precision, op_cat: eltwise, perf,2024-10-15T00:32:23Z -->
- [x] #13373<!-- ,PyTorch Tracing Sweeps,op_cat: eltwise, master, MCW,2024-10-16T12:45:55Z -->
- [x] #13374<!-- ,Integer support of eltwise ops,op_cat: eltwise,2024-10-02T15:52:23Z -->
- [x] #13385<!-- ,Optimize `ttnn.round` with a direct implementation,feature-request, op_cat: eltwise, perf,2024-10-17T09:35:25Z -->
- [x] #13415<!-- ,ttnn.bitwise_left_shift gives results different from the torch version when the bit used to represent a sign differs from the bit on position 31 - shift_bits,bug, WH, op_cat: eltwise,2024-10-03T09:39:58Z -->
- [x] #13521<!-- ,Pytorch Tracing sweeps - debugs & fixes,op_cat: eltwise, master, MCW,2024-10-17T06:38:20Z -->
- [x] #13544<!-- ,Values in (2^15, 2^23) are not rounded by rounding ops,bug, precision, op_cat: eltwise,2024-10-15T00:41:38Z -->
- [x] #14448


### Bugs: Operational Failures and Hangs
- [x]  #4702<!-- ,multiple ttnn operations hang when run many times in loop on WH cards,bug, WH, P1_critical, op_cat: eltwise,2024-10-01T00:15:12Z -->
- [x] #10144<!-- ,TTNN eltwise_logical_xor sweep test execution hangs (GS & WH),bug, GS, WH, op_cat: eltwise,2024-10-01T00:02:33Z -->


### Bugs: Low PCC Errors
- [x] ? #3309<!-- ,tt_lib.tensor.rpow fails with low PCC [Grayskull] [Doc],bug, GS, P2_should_have, op_cat: eltwise,2024-10-01T00:09:15Z -->
- [x] #3561<!-- ,ttl.tensor.recip operation breaks with low PCC [Wormhole] [Doc],bug, WH, P2_should_have, op_cat: eltwise,2024-10-01T00:09:33Z -->
- [x] #3612<!-- low pcc for negative values in exp -->
- [ ] * #4409<!-- ,isfinite, isinf, isposinf, isneginf and isnan fail with low PCC on Wormhole cards,bug, WH, P2_should_have, op_cat: eltwise,2024-06-05T07:29:11Z -->
- [x] #5893<!-- ,Some TTNN operations fail with low PCC error [Grayskull and Wormhole],bug, GS, WH, P2_should_have, op_cat: eltwise,2024-10-01T00:10:03Z -->
- [x] #6391<!-- ,ttnn.exp, exp2, expm1 and ldexp fail with low PCC on both GS and WH in larger value ranges [Bug Report][GS][WH],bug, GS, WH, P2_should_have, op_cat: eltwise,2024-05-08T14:13:14Z -->
- [x] #7749<!-- ,ttnn.signbit operation failed with low PCC [Grayskull and Wormhole],bug, GS, WH, ttnn, P2_should_have, op_cat: eltwise,2024-10-17T18:29:02Z -->
- [x] #8634<!-- ,ttnn.log, log2 and log10 operation fail with low PCC on TILE layout, bfloat8_b and random shapes like (198, 216),bug, GS, WH, LLK, op_cat: eltwise,2024-09-24T08:24:42Z -->
- [x]  #13675<!-- ,ttnn.tan_bw operation fails with low PCC,bug, op_cat: eltwise, backward,2024-10-10T11:33:50Z -->
- [x]  #13676<!-- ,ttnn.i0_bw operation fails with low PCC,bug, op_cat: eltwise, backward,2024-10-10T11:33:45Z -->
- [x]  #13739<!--,ttnn.cos_bw operation fails with low PCC on Grayskull,bug, GS, op_cat: eltwise, backward,2024-10-11T09:23:46Z -->
- [x] #13774<!-- ,ttnn.subalpha_bw low PCC,bug, GS, WH, op_cat: eltwise, backward,2024-10-14T13:36:01Z -->
- [x] #13776<!-- ,ttnn.hypot_bw low PCC,bug, GS, WH, op_cat: eltwise, backward,2024-10-14T13:48:19Z -->
- [x]  #13856<!-- ,ttnn.bias_gelu_bw unary low PCC,bug, GS, WH, op_cat: eltwise, backward,2024-10-16T08:40:22Z -->
- [x] #13929<!-- ,ttnn.ldexp_bw operation fails with low PCC,bug, GS, WH, op_cat: eltwise,2024-10-17T08:59:39Z -->
- [x] #13937<!-- ,ttnn.rdiv_bw low PCC,bug, GS, WH, op_cat: eltwise, backward,2024-10-17T10:54:34Z -->


### Unsupported dtypes
- [x]  #13626<!-- ,ttnn.lgamma operation does not work bfloat8_b,bug, op_cat: eltwise,2024-10-09T09:06:20Z -->
- [x]  #13674<!-- ,ttnn.acosh_bw operation does not work with bfloat8_b tensors,bug, op_cat: eltwise, backward,2024-10-17T09:01:32Z -->
- [x] #13927<!-- ,softshrink_bw operation does not work bfloat8_b,bug, GS, WH, op_cat: eltwise,2024-10-17T09:00:54Z -->
- [x]  #13926<!-- ,ttnn.logit_bw operation does not work bfloat8_b,bug, GS, WH, op_cat: eltwise,2024-10-17T09:01:08Z -->


### Documentation Issues
- [x] #14144 
- [x] #14145 
- [x] #14141 
- [x] #14293 
- [x] #14291 
- [x] #7487<!-- ,Improve documentation for ttnn glu, reglu, and geglu operations,GS, WH, op_cat: eltwise,2024-09-30T23:19:54Z -->
- [x] #7711<!-- ,TTNN hard*-alike ops - incomplete documentation,bug, P1_critical, op_cat: eltwise,2024-09-28T16:33:48Z -->
- [x] #7792<!-- ,TTNN trigonometric hyperbolic ops - wrong types info in documentation,bug, P1_critical, op_cat: eltwise,2024-09-26T05:58:46Z -->
- [x]  #7955<!-- ,TTNN log/exp-alike ops - incomplete documentation,bug, P1_critical, op_cat: eltwise, MCW,2024-10-01T00:57:51Z -->
- [x] #7957<!-- ,TTNN tensor creation ops - zeros, zeros_like, empty - incomplete documentation,bug, P2_should_have, op_cat: eltwise,2024-10-01T00:13:06Z -->
- [x] #7961<!-- ,TTNN logical binary ops - incomplete documentation,bug, P1_critical, op_cat: eltwise,2024-07-30T14:46:33Z -->
- [x] #7996<!-- ,TTNN sub and mul ops - incomplete/inconsistent documentation,bug, P1_critical, op_cat: eltwise,2024-10-17T10:44:01Z -->
- [x] #8142<!-- ,TTNN log-alike ops incomplete documentation,bug, op_cat: eltwise,2024-09-30T23:20:53Z -->
- [x] #8151<!-- ,TTNN reglu incomplete documentation,bug, op_cat: eltwise,2024-09-30T23:21:33Z -->
- [x] #8155<!-- ,TTNN multigammaln - incomplete documentation,bug, op_cat: eltwise,2024-09-30T23:22:05Z -->
- [x] #8156<!-- ,TTNN mish - incomplete documentation,bug, op_cat: eltwise,2024-09-30T23:22:28Z -->
- [x] #8157<!-- ,TTNN leaky relu - incomplete documentation,bug, op_cat: eltwise,2024-10-04T12:06:40Z -->
- [x] #8343<!-- ,tt_lib.tensor.glu, geglu, reglu, swiglu - inconsistent documentation,bug, op_cat: eltwise,2024-10-01T05:15:16Z -->
- [x] #10585<!-- ,TTNN backward ops - incomplete documentation,bug, op_cat: eltwise, op_cat: misc, backward, master, MCW,2024-08-07T05:50:20Z -->
- [x]  #11086<!-- ,Update documentation for Unary bw ops,bug, op_cat: eltwise, backward, MCW,2024-10-17T18:59:28Z -->
- [x] #13682<!-- ,Incomplete documentation for ttnn.normalize_global and ttnn.normalize_hw regarding input_tensor rank,GS, WH, op_cat: eltwise,2024-10-14T13:25:14Z -->
- [x] #13683<!-- ,ttnn.mul_bw unary inconsistent documentation regarding input tensors layout,GS, WH, op_cat: eltwise, backward,2024-10-16T08:33:34Z -->
- [x] #13685<!-- ,ttnn.embedding_bw inconsistent documentation regarding input tensors dtypes,WH, op_cat: eltwise, op_cat: embedding, backward,2024-10-16T07:22:12Z -->
- [x] #13674 
- [x] #13626 
- [x] #13926 
- [x] #14448 
- [x] #13977
