### ISSUE TITLE
"Async" CCLs Support Master Issue

### ISSUE THREAD

**Issue by SeanNijjar** [tenstorrent/tt-metal#14562]
- [ ] Linear Topology EDM Fabric
  - [ ] Chip Unicast command support
  - [ ] Chip Multicast command support
  - [ ] Noc Unicast
  - [ ] Noc Multicast
  - [ ] Noc Atomic Inc Command
  - [ ] Masked Writes (parallel with op bringup)
 
- [ ] (prefetch task) Bringup CCL command "CB_to_Tensor" (name to be workshopped :) ) in local mode
  - [ ] Adapt to `fabric write`s (unicast) Implement mcast on sender side to start after EDM fabric bringup
  - [ ] Update to mcast after chip mcast support added

- [ ] (prefetch task) Bringup CCL command "ccl shift tensor" for local writes
  - [ ] Adapt to `fabric_writes` after EDM fabric availability
  
- [ ] Enable new all-gather
  - CCL commands to read (reader kernel) and mcast tensor (writer kernel)
  - Add atomic inc at end of write
  
- [ ] Enable new all-reduce
  - sender kernels: ccl_shift commands in loop
    - then add mcast command for the last part
  - receivers: Read from input tensor and parked buffer tensor

- [ ] Enable new reduce-scatter:
  - writer: same as all-reduce excluding last mcast command, replaced with local output tensor write
  - reader: use existing CCL command to read tensor slices (because for reduce scatter, scatter dimension matters)

- [ ] Integrate Async All-gather into Llama
  - TODO: outline specific op instances here as itemized list

- [ ] Integrate Async All-reduce into Llama
  - TODO: outline specific op instances here as itemized list

- [ ] Integrate Async Reduce scatter into Llama
  - TODO: outline specific op instances here as itemized list

**Comment by SeanNijjar** [comment]
stale
