### ISSUE TITLE
[Master issue] Upgrade and maintain TT-NN sweeps infrastructure

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#15786]
- [ ] Verify that all ES features used by sweeps infrastructure is transferrable to AWS OpenSearch
- [ ] Bring up STS authentication via Entra SSO to AWS OpenSearch instance in sweeps infrastructure
- [ ] Confirm Python AWS OS client auto-renews STS session tokens, or build wrappers to do so in infra code
- [ ] Migrate CI to use AWS OS instance
- [ ] Plan and document access flow for TT-NN developers to access OS instance
- [ ] Plan and execute doubled-ES instance fleet
- [ ] Confirm to IT that access flows work, including SSO and timeouts

**Comment by tt-rkim** [comment]
Current issue is that CIv2 runners cannot connect to resources in cloud https://github.com/tenstorrent/tt-metal/actions/runs/14668224491/job/41169099364

Sweeps are essentially unusable until we can migrate to cloud.

**Comment by tt-rkim** [comment]
@stevendae Please follow up on this issue and let us know where the best final resting place for these TODOs would be.

**Comment by stevendae** [comment]
The thing holding up the sweeps infra is the data store location and based on current trajectories we're moving towards the data teams Postgres + Superset stack being that place. 

It's also possible that we will need to seek an additional data client to enable a key desired feature: failing test to gh issue association.

With this said, unless there are unexpected obstacles with the current trajectory there is no current desire/reason to bring up AWS Opensearch as we are moving in the Postgres / Superset direction.
