### ISSUE TITLE
Migrate hugepages configuration to tt-system-tools method

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#15952]
# Summary 
New improved method to correctly configure hugepages on Tenstorrent systems has been provided.

https://github.com/tenstorrent/tt-system-tools/tree/main

This is already planned to be the recommended path for customers.

We need to ensure we are using this in CI.

# Tasks

- [ ] [Update provisioning workflows to use new method](https://github.com/tenstorrent-metal/metal-internal-workflows/pull/327)
- [ ] [Adapt tt-metal repo to be ready for new hugepages](https://github.com/tenstorrent/tt-metal/pull/14396)
- [ ] [Update already provisioned systems](https://github.com/tenstorrent/tt-metal/issues/15675)
  - [ ] Grayskull VMs
  - [ ] Wormhole VMs
  - [ ] Blackhole VMs
  - [ ] T3K VMs
  - [ ] TG / TGG systems
  - [ ] Baremetals ?
- [ ] Verify that updated systems have no problems in all-post-commit or other pipelines 
- [ ] [Update `setup_dependencies.sh` to install hugepages for customers](https://github.com/tenstorrent/tt-metal/pull/15953)
- [ ] [Update documentation](https://github.com/tenstorrent/tt-metal/issues/15954)
