### ISSUE TITLE
OSS Doc Sprint Feedback Master Tracker

### ISSUE THREAD

**Issue by chekangliang** [tenstorrent/tt-metal#3905]
The issue is to do the warm hand off to @mo-tenstorrent for the following drafts of documentation that requires review and sign-off.

Pending: 

- [x] matmul_multi_core link: https://tenstorrent-metal.github.io/tt-metal/latest/tt_metal/examples/matmul_multi_core.html (eta: 11/22)
- [x] watcher link: https://tenstorrent-metal.github.io/tt-metal/latest/tools/watcher.html (eta: 11/22)
- [x] tracy_host_profiler link: https://tenstorrent-metal.github.io/tt-metal/latest/tools/tracy_host_profiler.html (eta: 11/22)
- [x] device side profiler link: https://tenstorrent-metal.github.io/tt-metal/latest/tools/device_program_profiler.html (eta: 11/22)
- [x] TTNN Tutorials - mha (optimized) https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/tutorials/ttnn_tutorials/003.html#Write-optimized-version-of-Multi-Head-Attention (eta: ??)

In progress: 

- [x]  #3770  link: https://tenstorrent-metal.github.io/tt-metal/latest/tools/kernel_print.html
- [ ] #3752 Tutorial: https://tenstorrent-metal.github.io/tt-metal/latest/ttnn/tutorials/multihead-attention.html

**Comment by fahmedchanTT** [comment]
Closing as no longer relevant.
