### ISSUE TITLE
[On Hold] Tests with input dataset

### ISSUE THREAD

**Issue by boris-drazic** [tenstorrent/tt-metal#4351]
Make tests for models that will use appropriate validation data set (e.g., SQUAD, hellaswag) to run model and compare output to expected outputs from data set.
This tests should be organized in a similar way to `models/experimental/mistral/tests/test_perf_accuracy_mistral.py`.
Here is list of models to make tests for

Priority:
- [x] bloom   **[Punith]** [PR #4772](https://github.com/tenstorrent-metal/tt-metal/pull/4772) [Merged]
- [x] t5   **[Vignesh]**  [PR #4500](https://github.com/tenstorrent-metal/tt-metal/pull/4500) [Update needed]
- [x] whisper   **[Punith]** [PR #4501](https://github.com/tenstorrent-metal/tt-metal/pull/4501) [Pending CI]

Rest:
- [x] yolov5 **[Keerthana]** [PR #4776](https://github.com/tenstorrent-metal/tt-metal/pull/4776) [Pending CI]
- [x] swin **[Jayasurya]** [PR #4774](https://github.com/tenstorrent-metal/tt-metal/pull/4774) [Merged]
- [x] llama **[Jayasurya]** [PR #4717](https://github.com/tenstorrent-metal/tt-metal/pull/4774)
- [x] trocr **[Jayasurya]** [commit](https://github.com/tenstorrent-metal/tt-metal/commit/76add4d01396a4c2a6535b0a4484f86e39f681d3) [To verify on main]
- [x] ssd **[Keerthana]** [PR #4585](https://github.com/tenstorrent-metal/tt-metal/pull/4585) [Merged]
- [x] yolov3 **[Keerthana]** [PR #4719](https://github.com/tenstorrent-metal/tt-metal/pull/4719) [Merged]
- [x] roberta **[Keerthana]** [PR #4627](https://github.com/tenstorrent-metal/tt-metal/pull/4627) [Merged]
- [x] deit **[Keerthana]** [PR #4628](https://github.com/tenstorrent-metal/tt-metal/pull/4628) [Merged]
- [x] efficientnet **[Jayasurya]** [PR #4633](https://github.com/tenstorrent-metal/tt-metal/pull/4633) [Merged]
- [x] vit **[Sudharsan]** [PR #4749](https://github.com/tenstorrent-metal/tt-metal/pull/4749) [Merged]
- [x] distilbert   **[Keerthana]** [PR #4510](https://github.com/tenstorrent-metal/tt-metal/pull/4510) [Merged]
- [x] mnist   **[Jayasurya]** [PR #4502](https://github.com/tenstorrent-metal/tt-metal/pull/4502) [Merged]
- [x] lenet **[Jayasurya]** [PR #4634](https://github.com/tenstorrent-metal/tt-metal/pull/4634) [Merged]

Don't do:
- [x] llama2 (no TT implementation)

**Comment by saichandax** [comment]
Currently, only 5 models are pending at different levels.
- [x] t5   **[Vignesh]**  [PR #4500](https://github.com/tenstorrent-metal/tt-metal/pull/4500) [Update needed]
- [x] whisper   **[Punith]** [PR #4501](https://github.com/tenstorrent-metal/tt-metal/pull/4501) [Pending CI]
- [x] yolov5 **[Keerthana]** [PR #4776](https://github.com/tenstorrent-metal/tt-metal/pull/4776) [Pending CI]
- [ ] llama **[Jayasurya]** [To create PR]
- [x] trocr **[Jayasurya]** [commit](https://github.com/tenstorrent-metal/tt-metal/commit/76add4d01396a4c2a6535b0a4484f86e39f681d3) [To verify on main]

The work will be resumed once Stable Diffusion tasks are done #4765

**Comment by saichandax** [comment]
Nothing pending. Closing this issue.
