### ISSUE TITLE
[Master Issue] Introduce Docker Ecosystem

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#8418]
Master list of issues for docker integration

- [x] #7944 
- [x] #8082 
- [ ] #8550
- [ ] #11974
- [ ] #11973
- [x] push to ghcr
- [] long term artifact referencing for caching
- [x] #9084 include working virtual env
- [x] #10469 
- [ ] #12495
- [ ] #12496
- [ ] #11462 
- [ ] #11762

**Comment by ttmchiou** [comment]
@dimitri-tenstorrent

**Comment by JushBJJ** [comment]
Could you guys also add a way to `docker compose` as well?

**Comment by TT-billteng** [comment]
closing in favor of https://github.com/tenstorrent/tt-metal/milestone/
