### ISSUE TITLE
Multiprocess Support Top Level Checklist

### ISSUE THREAD

**Issue by vtangTT** [tenstorrent/tt-metal#8730]
- [x] https://github.com/tenstorrent/tt-metal/issues/8729
- [x] Investigate why Pytest SIGALRM does not always work -> because of python GIL
- [x] https://github.com/tenstorrent/tt-metal/issues/9314
- [ ] Investigate multiprocess support at `CreateDevice` or `tt_cluster` level

cc: @TT-billteng @tapspatel @tt-rkim

**Comment by tt-rkim** [comment]
Ah! This will probably mean running our tests in a separate process from the pytest executor.

That will be a pretty big shift in how we do things.
