### ISSUE TITLE
Complete checklist for Wormhole and T3000 readiness (examples, docs, and instructions)

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#8764]
- [x] Add disclaimer to README models that they were only tested on N300
- [x] Go through https://tenstorrent.github.io/tt-metal/latest/tt-metalium/get_started/get_started.html and other programming examples for metal/nn and see what works on both N150 and N300
- [x] Go through current marketed models on front page, `models/wormhole`, and current N300 nightly regression and see what works on N150
- [x] Add columns to current marketed models on front page for N150 + N300, working or not (or separate tables, or asterisks for perf etc)
- [x] Add working N150 models to the CI for automated testing 
- [x] Test/add no-WH disclaimers for ttnn tutorials/code snippets (ignore API ref for now)
- [x] Split + finalize separate "First things to do" lists for metalium and nn separately. Right now they're together.
- [x] Ensure "First things to do" list works for both N150 and N300 / create a new list altogether different from Grayskull
- [x] Copy installation instructions into both metalium and nn Sphinx docs, but keep source in INSTALLING.md (symlinking, change to rst etc)
- [x] https://github.com/tenstorrent/tt-metal/pull/7999 , pending SysEng approves the release (EDIT: Change to v80.9.3.0)
- [x] Check the documentation here and clearly mark if its working on n150, n300 or both: https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/usage.html
- [x] Check the documentation here and clearly mark if its working on n150, n300 or both: https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/tutorials.html
- [x] Check the documentation here and clearly mark if its working on n150, n300 or both: https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/converting_torch_model_to_ttnn.html
- [x] Check the documentation here and clearly mark if its working on n150, n300 or both: https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/adding_new_ttnn_operation.html
- [x] Add two more things to do with tt-metalium making the total count 5 here: https://tenstorrent.github.io/tt-metal/latest/tt-metalium/get_started/get_started.html
- [x] Remove this section from the docs as it points to some internal references: https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/converting_torch_model_to_ttnn.html#more-examples
- [x] Add items to first 5 things to do with n150 and n300: https://tenstorrent.github.io/tt-metal/latest/ttnn/ttnn/get_started.html
- [x] Complete https://github.com/tenstorrent/tt-metal/issues/8965 and add WH example tests for ttnn for it so CI can catch future issues
- [x] Re-format units on front page to be consistent / nicer to look at (collab w/ aho)
- [x] Work on feedback from https://github.com/tenstorrent/tt-metal/issues/9092
- [x] Work on feedback from https://github.com/tenstorrent/tt-metal/issues/9127
- [x] https://github.com/tenstorrent/tt-metal/issues/9258
- [x] https://github.com/tenstorrent/tt-metal/pull/9257
- [ ] https://github.com/tenstorrent/tt-metal/issues/9305
- [x] Create release
- [x] Add note to README that perf #s for WH are from N300
- [x] Add source-only warnings to tools and add a link to profiler in first things to do in metalium with the same warning
- [ ] Add some more clarification on what env vars to set for ttnn only + whl / models + whl / source.
- [x] https://github.com/tenstorrent/tt-metal/issues/9945
- [x] Attempt upgrade to `v80.9.3.0` and roll out to installation instructions (MIW 256)
- [x] Add note about SD on N300
- [x] #10283 
- [x] #10305 
- [x] https://github.com/tenstorrent/tt-metal/issues/10485
- [x] https://github.com/tenstorrent/tt-metal/issues/10765
- [ ] https://github.com/tenstorrent/tt-metal/issues/11298

cc: @mbahnasTT @adifrancescoTT @Shubhamsaboo @TT-billteng

**Comment by tt-rkim** [comment]
Fixed up a lot of documentation to dos today

BERT Large batch 7 and Mamba on the front page should be working on N300.

The other two have errors.

haven't started on N150

**Comment by tt-rkim** [comment]
Closing.

Remaining are:

- a benchmark docs issue where we want to auto update w/ numbers
- Instructions improvements for the wheel which have an open issue
