### ISSUE TITLE
Complete optional output tensors and add queue_id

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#9123]
The following ops need to have both the optional output tensors and the queue_id added
See requirements here: https://docs.google.com/document/d/1Fq16tzk7VK9Lja9dQR1zLD4ABmWsvorEyOqxSo55484/

**Ops status tracker** : https://docs.google.com/spreadsheets/d/1UyF0Uh2bx8SZnb_L9g2M7Cc5XkuMrt4VpPp_R7pJyQo/edit?usp=sharing

- [x] #12615
- [x] #12065
- [x] #12688
- [x] #12164
- [x] #12148
- [x] #12435
- [x] #12758
- [x] Add queue_id and optional output tensors to ttnn.gelu
- [x] #12375 
- [x] #12297
- [x] #12137
- [x] #12373
- [x] #12147
- [x] #12146
- [x] #12224
- [x] #9110 
- [x] #9149
- [x] #9151
- [x] #9152
- [x] #9340
- [x] #12556
- [x] ElemwiseUnary/ELEMWISE_UNARY_ADD #9334 
- [x] ElemwiseUnary/ELEMWISE_UNARY_DIV #9334 
- [x]  ElemwiseUnary/ELEMWISE_UNARY_MUL #9339
- [x] ElemwiseUnary/ELEMWISE_UNARY_FILL #9333 
- [x] ElemwiseUnary/ELEMWISE_UNARY_FILLZERO #9333 
- [x] Unary ops #9484 
- [x]  ElemwiseUnary/ELEMWISE_UNARY_EXP #9494 
- [x] ElemwiseUnary/ELEMWISE_UNARY_POW #9494 
- [x] ElemwiseUnary/ELEMWISE_UNARY_SQRT #9494 
- [x] ElemwiseUnary/ELEMWISE_UNARY_TANH #9494 
- [ ] Unary backward ops #9483 

**Dependencies requiring optional output tensors and queue_id :** 

- [x] #12374
- [x] #12425
- [ ] #12384
- [x] #12245
- [x] Add queue_id and optional output tensors to subalpha_bw
- [x] #12763

Non-eltwise ops
- [ ] #9147
- [x] #9150
- [ ] #12343
- [x] #12344
- [ ] #12345
- [ ] #9148

**Comment by KalaivaniMCW** [comment]
Tracking the list of dependent ops that were added support here: 
- [ ] #9217 

- bcast
