### ISSUE TITLE
Create benchmarking tools for tracking run and measurement data in tt-metal model tests

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#9648]
Create a set of utility functions for logging info/statistics in model tests. These utility functions should create CSV artifacts that will be ingested by CI for tracking in subsequent infra tools. The tools should be initially tested on model demos as they are key deliverables.

- [x] Create custom profiler to adhere to standards for timestamps
- [x] Create custom class for adding measurements and saving run/measurement CSVs
- [x] Create a demo utility function for adding relevant measurement data
- [x] Create demo utility functions for verifying tokens and perf against targets
- [x] Test benchmarking tools on the Falcon7b demo

cc @uaydonat
